package giomar.rodriguez.com.laradio.model

data class Station(
    var id: Int,
    var name: String,
    var url: String,
    var logoUrl: String,
    var frequency: String,
    var ciudad: String,
    var isFavorite: Boolean,
    var isLiked: Boolean
)

object Supplier {
    val stations = listOf<Station>(
        Station(1,
            "La Bacana", "http://radio.domint.net:8238/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2015/05/labakanafm.jpg",
            "105.9", "Santiago",
            false,
            false),
        Station(2,
            "Monumental", "http://stm2.grupointernet.com:8103/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/monumental-100.3-fm.jpg",
            "100.3", "Santiago",
            false,
            false),
        Station(3,
            "Disco 89", "http://radio2.rgradio.net:9020/disco89.mp3",
            "http://radiosdominicanas.com/wp-content/uploads/2014/05/disco-88.9-fm-logo.jpg",
            "89", "Santiago",
            false,
            false),
        Station(4,
            "Turbo", "http://streaming.turbo98.com:7020/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2015/05/turbo-98-fm-logo.jpg",
            "98.3", "Santiago",
            false,
            false),
        Station(5,
            "Criolla", "http://rgradio.net:8060/criolla106.mp3",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/criolla-106.jpg",
            "106.1", "Santiago",
            false,
            false),
        Station(6,
            "Poder", "http://50.63.8.141:9000/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2015/05/poder98.jpg",
            "98.7", "Santiago",
            false,
            false),
        Station(7,
            "La Bacana", "http://radio.domint.net:8124/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/labakana.jpg",
            "105.7", "Santo Domingo",
            false,
            false),
        Station(8,
            "Disco", "http://radio2.domint.net:8048/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/05/disco-106-fm-logo.jpg",
            "106", "Santo Domingo",
            false,
            false),
        Station(9,
            "Z 101", "http://14943.live.streamtheworld.com/Z101FM.mp3",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/z101-fm.jpg",
            "101", "Santo Domingo",
            false,
            false),
        Station(10,
            "Caliente", "http://radio7a.domint.net:8064/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/05/caliente-fm.jpg",
            "104.1", "Santo Domingo",
            false,
            false),
        Station(11,
            "Zol", "http://radio2.domint.net:8240/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/zol-106.5-fm.jpg",
            "106.5", "Santo Domingo",
            false,
            false),
        Station(12,
            "Escandalo", "http://radio.domint.net:8062/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2014/06/escandalo-97.3-fm.jpg",
            "107.3", "Santo Domingo",
            false,
            false),
        Station(13,
            "Ritmo", "http://streaming.ritmo96.com:7100/;/stream/1",
            "http://radiosdominicanas.com/wp-content/uploads/2015/05/ritmo-96.5-fm.jpg",
            "105.7", "Santo Domingo",
            false,
            false)
    )
}